import {
  CalendarDays,
  Camera,
  CheckCircle2,
  CreditCard,
  Flower2,
  PartyPopper,
  Salad,
  Sprout,
  Ticket,
  Users,
  WalletCards,
} from "lucide-react";

export const patterns = {
  neumorphism: {
    key: "neumorphism",
    name: "ふんわり予約",
    background: "#E4EBF2",
    pattern: "none",
    primary: "#5B8FC9",
    secondary: "#6BB89E",
    gradientFrom: "#6BA3D6",
    gradientTo: "#4A82B8",
    heading: "#2C3A4C",
    text: "#364152",
    muted: "#6B7B8D",
    border: "rgba(200,212,226,0.6)",
    surface: "#E4EBF2",
    tint: "#ECF1F7",
    chip: "#D6E2EE",
    chipText: "#4A78A0",
    shadow: "6px 6px 14px rgba(163,177,198,0.45), -6px -6px 14px rgba(255,255,255,0.8)",
    bgImage: "/mock-assets/bg/blue-sky-pexels.jpg",
    hero: {
      eyebrow: "蒲郡オレンジパーク",
      headline: "今日は、くだもの日和。",
      lead: "旬の果物と、おいしい時間。蒲郡で気軽な一日を。",
      cta: "おでかけを選ぶ",
      image: "/mock-assets/booking-top/orange-orchard-worker-pexels.jpg",
      benefits: [
        ["旬を味わう", "枝先の色づきが、旅のごほうびに。", Sprout],
        ["おいしい時間", "食事まで含めて、ゆっくり一日。", Salad],
        ["季節の寄り道", "その日だけの味に出会う。", CalendarDays],
      ],
    },
    copy: {
      planEyebrow: "旬のプラン",
      planTitle: "どの体験にする？",
      planCta: "日時を選ぶ",
      dateEyebrow: "日程",
      dateTitle: "いつ行く？",
      dateCta: "予約者情報へ",
      accountEyebrow: "あと少し",
      accountTitle: "予約者情報へ進む",
      memoEyebrow: "ひとこと",
      memoTitle: "ひとこと添える",
      paymentEyebrow: "お支払い",
      paymentTitle: "支払い方法",
      paymentCta: "内容を確認する",
      confirmEyebrow: "最終確認",
      confirmTitle: "旅程を確認",
      confirmCta: "予約を確定する",
      completeLine1: "フルーツ旅、準備完了。",
      completeLine2: "当日は蒲郡で会いましょう。旬の香りが待っています。",
    },
  },
  glassmorphism: {
    key: "glassmorphism",
    name: "光のフルーツ旅",
    background: "#E6ECE2",
    pattern: "none",
    primary: "#D96030",
    secondary: "#2A9D8F",
    gradientFrom: "#E87040",
    gradientTo: "#C85020",
    heading: "#1A2E1C",
    text: "#1E2D20",
    muted: "#5A7060",
    border: "rgba(255,255,255,0.45)",
    surface: "rgba(255,255,255,0.55)",
    tint: "rgba(255,255,255,0.3)",
    chip: "rgba(255,255,255,0.5)",
    chipText: "#2A7D6F",
    shadow: "0 16px 40px rgba(30,60,40,0.12)",
    bgImage: "/mock-assets/bg/orchard-pexels.jpg",
    hero: {
      eyebrow: "初夏のフルーツシーズン",
      headline: "採る、食べる、笑う。",
      lead: "木漏れ日の果樹園で、旬の一粒を。",
      cta: "旬の体験を見る",
      image: "/mock-assets/booking-top/family-strawberry-harvest-pexels-paloma-rodriguez.jpg",
      benefits: [
        ["みんなで楽しい", "小さな発見が、帰り道の話題に。", Users],
        ["写真に残る一日", "採る瞬間も、食べる時間も。", Camera],
        ["日帰りの特別", "近場のおでかけを、旅に変える。", PartyPopper],
      ],
    },
    copy: {
      planEyebrow: "体験を選ぶ",
      planTitle: "旬を選ぶ",
      planCta: "この体験を選ぶ",
      dateEyebrow: "旅の日程",
      dateTitle: "旅の日を決める",
      dateCta: "予約者情報へ",
      accountEyebrow: "あと少しで旅の予定が決まる",
      accountTitle: "予約者情報",
      memoEyebrow: "来園前のひとこと",
      memoTitle: "ひとこと添える",
      paymentEyebrow: "お支払い",
      paymentTitle: "支払いを選ぶ",
      paymentCta: "旅程を確認する",
      confirmEyebrow: "最終確認",
      confirmTitle: "予約内容の確認",
      confirmCta: "予約を確定する",
      completeLine1: "蒲郡で会いましょう。",
      completeLine2: "旬の香りと笑顔が、あなたを待っています。",
    },
  },
  bento: {
    key: "bento",
    name: "旬のベントー",
    background: "#FAF5EE",
    pattern: "none",
    primary: "#D45B2C",
    secondary: "#2D8C5A",
    gradientFrom: "#E06830",
    gradientTo: "#B84820",
    heading: "#2A1A0E",
    text: "#302418",
    muted: "#7A6A58",
    border: "#E8DCC8",
    surface: "#FFFFFF",
    tint: "#F5EDE0",
    chip: "#E8F4E0",
    chipText: "#2D7A4A",
    shadow: "0 8px 24px rgba(80,50,20,0.1)",
    bgImage: "/mock-assets/bg/road-trip-pexels.jpg",
    hero: {
      eyebrow: "蒲郡オレンジパーク 2026",
      headline: "旬を選んで、蒲郡へ。",
      lead: "家族の週末に、甘い予定を。",
      cta: "旬のチケットを見る",
      image: "/mock-assets/booking-top/orange-tree-couple-pexels-tran-le-tuan.jpg",
      benefits: [
        ["季節を選ぶ", "いまだけの味わいを、旅のきっかけに。", Ticket],
        ["旅支度を軽く", "行きたい気持ちで、すぐ予約。", CheckCircle2],
        ["蒲郡らしさ", "柑橘と緑に囲まれる一日。", Flower2],
      ],
    },
    copy: {
      planEyebrow: "旬のプラン",
      planTitle: "旬のプラン",
      planCta: "このプランにする",
      dateEyebrow: "日時と人数",
      dateTitle: "日時と人数",
      dateCta: "予約者情報へ",
      accountEyebrow: "予約者情報",
      accountTitle: "予約者情報",
      memoEyebrow: "連絡事項",
      memoTitle: "連絡事項",
      paymentEyebrow: "お支払い",
      paymentTitle: "支払い方法",
      paymentCta: "この内容で確認する",
      confirmEyebrow: "予約確認",
      confirmTitle: "予約内容の確認",
      confirmCta: "この内容で予約する",
      completeLine1: "予約完了。",
      completeLine2: "当日をお楽しみに。蒲郡で素敵な一日をお過ごしください。",
    },
  },
};

export const patternFallback = {
  "fruit-trip": "neumorphism",
  "family-fun": "glassmorphism",
  "seasonal-ticket": "bento",
  vibrant: "neumorphism",
  premium: "glassmorphism",
  festival: "bento",
  "ui-clarity": "neumorphism",
  "visual-travel": "glassmorphism",
};

export const plans = [
  {
    id: "cherry",
    title: "さくらんぼ狩り",
    pr: "枝先の旬を、その場で。",
    image: "/mock-assets/booking-top/orange-orchard-worker-pexels.jpg",
  },
  {
    id: "kama",
    title: "釜飯とフルーツ狩り",
    pr: "おいしい食事と旬の味わいを。",
    image: "/mock-assets/booking-top/orange-tree-couple-pexels-tran-le-tuan.jpg",
  },
  {
    id: "family",
    title: "みんなで収穫体験",
    pr: "家族で採って食べて笑う一日。",
    image: "/mock-assets/booking-top/family-strawberry-harvest-pexels-paloma-rodriguez.jpg",
  },
];

export const dateOptions = ["5/24 土", "5/25 日", "5/31 土", "6/1 日"];
export const timeOptions = ["10:00", "11:00", "12:00", "13:00"];

export const paymentOptions = [
  ["localPay", "当日現地払い", "受付でお支払い。", WalletCards],
  ["credit", "クレジットカード", "事前決済で、当日は身軽に。", CreditCard],
];
