import {
  CalendarDays,
  Camera,
  CheckCircle2,
  Clock3,
  Compass,
  CreditCard,
  LifeBuoy,
  Mail,
  ShieldCheck,
  Ticket,
  UserRound,
  Users,
  WalletCards,
} from "lucide-react";

const appBaseUrl =
  typeof document === "undefined"
    ? import.meta.env.BASE_URL
    : new URL(import.meta.env.BASE_URL, document.baseURI).href;
const asset = (path) => new URL(path.replace(/^\/+/, ""), appBaseUrl).href;

const designSystemCopy = ({
  planEyebrow,
  planTitle,
  planCta,
  dateEyebrow,
  dateTitle,
  accountEyebrow = "予約者情報",
  paymentEyebrow = "お支払い",
  confirmEyebrow = "予約確認",
  completeLine1,
  completeLine2,
}) => ({
  planEyebrow,
  planTitle,
  planCta,
  dateEyebrow,
  dateTitle,
  dateCta: "予約者情報へ",
  accountEyebrow,
  accountTitle: "予約者情報",
  memoEyebrow: "連絡事項",
  memoTitle: "連絡事項",
  paymentEyebrow,
  paymentTitle: "支払い方法",
  paymentCta: "この内容で確認する",
  confirmEyebrow,
  confirmTitle: "予約内容の確認",
  confirmCta: "この内容で予約する",
  completeLine1,
  completeLine2,
});

export const patterns = {
  bento: {
    key: "bento",
    name: "Bento",
    background: "#FAF5EE",
    pattern: "none",
    primary: "#D45B2C",
    secondary: "#2D8C5A",
    gradientFrom: "#E06830",
    gradientTo: "#B84820",
    heading: "#2A1A0E",
    text: "#302418",
    muted: "#7A6A58",
    border: "#E8DCC8",
    surface: "#FFFFFF",
    tint: "#F5EDE0",
    chip: "#E8F4E0",
    chipText: "#2D7A4A",
    shadow: "0 8px 24px rgba(80,50,20,0.1)",
    bgImage: asset("mock-assets/bg/reservation-soft-grid.svg"),
    hero: {
      eyebrow: "Sample Booking 2026",
      headline: "行きたい体験を、すぐ予約。",
      lead: "イベント、見学、ワークショップなど、日付と人数を選んでスムーズに申し込める予約画面です。",
      cta: "体験プランを見る",
      image: asset("mock-assets/booking-top/reservation-calendar.svg"),
      benefits: [
        ["体験を選ぶ", "目的に合うプランを、短い説明と写真で見比べられます。", Ticket],
        ["日時を決める", "候補日と時間を選ぶだけで、予定がすぐ形になります。", CalendarDays],
        ["当日まで確認", "予約内容を最後に見直して、受付まで安心して進めます。", CheckCircle2],
      ],
    },
    copy: {
      planEyebrow: "予約プラン",
      planTitle: "参加したいプランを選ぶ",
      planCta: "このプランにする",
      dateEyebrow: "日時と人数",
      dateTitle: "日時と人数",
      dateCta: "予約者情報へ",
      accountEyebrow: "予約者情報",
      accountTitle: "予約者情報",
      memoEyebrow: "連絡事項",
      memoTitle: "連絡事項",
      paymentEyebrow: "お支払い",
      paymentTitle: "支払い方法",
      paymentCta: "この内容で確認する",
      confirmEyebrow: "予約確認",
      confirmTitle: "予約内容の確認",
      confirmCta: "この内容で予約する",
      completeLine1: "予約完了。",
      completeLine2: "当日は予約番号を受付で提示してください。ご来場をお待ちしています。",
    },
  },
  craft: {
    key: "craft",
    name: "Craft",
    background: "#FAF6F0",
    pattern: "paper",
    primary: "#FF914D",
    secondary: "#6F8F6A",
    gradientFrom: "#FF914D",
    gradientTo: "#D35400",
    heading: "#2B2A27",
    text: "#2B2A27",
    muted: "#6F675C",
    border: "#2B2A27",
    surface: "#FFFDF8",
    tint: "#F3E9D8",
    chip: "#D2E9CB",
    chipText: "#2F653A",
    shadow: "5px 5px 0 #2B2A27",
    bgImage: asset("mock-assets/bg/reservation-paper.svg"),
    hero: {
      eyebrow: "Sample Booking",
      headline: "今日の予定を、手帖に貼るように。",
      lead: "家族のおでかけ、学びの体験、少人数イベントまで。あたたかい雰囲気で予約を進められます。",
      cta: "体験を選ぶ",
      image: asset("mock-assets/booking-top/reservation-family.svg"),
      benefits: [
        ["選びやすい", "参加イメージが伝わる説明で、迷わずプランを決められます。", Ticket],
        ["家族で使いやすい", "人数変更や時間選択を大きなボタンで操作できます。", Users],
        ["連絡事項も添える", "ベビーカーや食事など、当日の相談を書き添えられます。", ShieldCheck],
      ],
    },
    copy: {
      planEyebrow: "体験メニュー",
      planTitle: "どの体験にする？",
      planCta: "この体験で日時へ",
      dateEyebrow: "参加日",
      dateTitle: "行きたい日を選ぶ",
      dateCta: "予約者情報へ",
      accountEyebrow: "ご連絡先",
      accountTitle: "予約者情報",
      memoEyebrow: "ご要望",
      memoTitle: "事前に伝えておきたいこと",
      paymentEyebrow: "お支払い",
      paymentTitle: "支払い方法",
      paymentCta: "内容を確認する",
      confirmEyebrow: "最終確認",
      confirmTitle: "予約内容の確認",
      confirmCta: "この内容で予約する",
      completeLine1: "予定が入りました。",
      completeLine2: "確認メールの内容を見ながら、当日は受付へお越しください。",
    },
  },
  studio: {
    key: "studio",
    name: "Studio",
    background: "#FBFBF9",
    pattern: "grid",
    primary: "#C85A32",
    secondary: "#B28E46",
    gradientFrom: "#C85A32",
    gradientTo: "#0F141C",
    heading: "#111111",
    text: "#1A1A19",
    muted: "#72716B",
    border: "#E2E2DC",
    surface: "#FFFFFF",
    tint: "#F2F1EC",
    chip: "#F6F2E8",
    chipText: "#8A4A30",
    shadow: "0 24px 70px rgba(15,20,28,0.08)",
    bgImage: asset("mock-assets/bg/reservation-soft-grid.svg"),
    hero: {
      eyebrow: "SELECT YOUR EXPERIENCE",
      headline: "体験の雰囲気を見ながら、ゆっくり選ぶ。",
      lead: "写真、料金、時間帯を落ち着いて確認しながら、予約完了まで一画面ずつ進めます。",
      cta: "プランを見てみる",
      image: asset("mock-assets/booking-top/reservation-lounge.svg"),
      benefits: [
        ["ビジュアルで選ぶ", "体験の雰囲気を見ながら、プランを比較できます。", Camera],
        ["確認しやすい", "日時、人数、支払い方法を最後にまとめて確認できます。", CheckCircle2],
        ["落ち着いた導線", "次に何をすればよいかがわかる予約フローです。", ShieldCheck],
      ],
    },
    copy: {
      planEyebrow: "RECOMMENDED",
      planTitle: "気になるプランを選ぶ",
      planCta: "このプランで日時へ",
      dateEyebrow: "DATE",
      dateTitle: "行きたい日時を選ぶ",
      dateCta: "予約者情報へ",
      accountEyebrow: "CONTACT",
      accountTitle: "予約者情報",
      memoEyebrow: "REQUEST",
      memoTitle: "連絡事項",
      paymentEyebrow: "PAYMENT",
      paymentTitle: "支払い方法",
      paymentCta: "予約内容を確認する",
      confirmEyebrow: "CONFIRM",
      confirmTitle: "予約内容の確認",
      confirmCta: "予約を確定する",
      completeLine1: "予約を承りました。",
      completeLine2: "受付で予約番号をお伝えください。スタッフがご案内します。",
    },
  },
  puerto: {
    key: "puerto",
    name: "Puerto",
    background: "#F8FAFC",
    pattern: "platform",
    primary: "#0A2540",
    secondary: "#00D4B2",
    gradientFrom: "#0A2540",
    gradientTo: "#12375C",
    heading: "#0A2540",
    text: "#0F172A",
    muted: "#475569",
    border: "#E2E8F0",
    surface: "#FFFFFF",
    tint: "#F1F5F9",
    chip: "#E6F7F4",
    chipText: "#0A6F60",
    shadow: "0 8px 16px rgba(15, 23, 42, 0.08)",
    bgImage: asset("mock-assets/bg/reservation-platform.svg"),
    hero: {
      eyebrow: "Puerto Reservation",
      headline: "空きを見て、すぐ予約。",
      lead: "日時と人数を順番に確認できます。",
      cta: "予約できるプランを見る",
      image: asset("mock-assets/booking-top/reservation-platform.svg"),
      benefits: [
        ["空きが見やすい", "候補日と時間を、一覧で落ち着いて確認できます。", Clock3],
        ["入力が進めやすい", "必要な項目だけを、順番に迷わず入力できます。", Compass],
        ["当日まで安心", "予約内容と支払い方法を最後にしっかり確認できます。", LifeBuoy],
      ],
    },
    copy: {
      planEyebrow: "PLAN",
      planTitle: "予約するプランを選択",
      planCta: "日時選択へ進む",
      dateEyebrow: "DATE & GUESTS",
      dateTitle: "日時と人数を選択",
      dateCta: "予約者情報へ進む",
      accountEyebrow: "ACCOUNT",
      accountTitle: "予約者情報の入力方法",
      memoEyebrow: "REQUEST",
      memoTitle: "連絡事項",
      paymentEyebrow: "PAYMENT",
      paymentTitle: "支払い方法を選択",
      paymentCta: "予約内容を確認する",
      confirmEyebrow: "CONFIRM",
      confirmTitle: "予約内容の確認",
      confirmCta: "予約を確定する",
      completeLine1: "予約が完了しました。",
      completeLine2: "確認メールをお送りしました。当日は受付で予約番号をお伝えください。",
    },
  },
  material: {
    key: "material",
    name: "Material",
    background: "#FFFBFE",
    pattern: "material",
    primary: "#6750A4",
    secondary: "#625B71",
    gradientFrom: "#6750A4",
    gradientTo: "#7D5260",
    heading: "#1D1B20",
    text: "#1D1B20",
    muted: "#5F5B66",
    border: "#E7E0EC",
    surface: "#FFFFFF",
    tint: "#F3EDF7",
    chip: "#EADDFF",
    chipText: "#4F378B",
    shadow: "0 8px 20px rgba(103, 80, 164, 0.16)",
    bgImage: asset("mock-assets/bg/reservation-soft-grid.svg"),
    hero: {
      eyebrow: "Material Booking",
      headline: "スマホで迷わず、次の体験へ。",
      lead: "タスクカード、下部アクション、状態表示を軸にしたモバイルファーストの予約画面です。",
      cta: "予約タスクを始める",
      image: asset("mock-assets/booking-top/reservation-calendar.svg"),
      benefits: [
        ["現在地がわかる", "次に選ぶ項目と完了済みの内容がはっきり見えます。", CheckCircle2],
        ["片手で進める", "主要操作を下部に置き、スマホでも進行しやすくします。", Compass],
        ["状態に強い", "未選択、入力中、完了の差を色と面で伝えます。", ShieldCheck],
      ],
    },
    copy: designSystemCopy({
      planEyebrow: "TASK",
      planTitle: "予約タスクを選択",
      planCta: "日時タスクへ進む",
      dateEyebrow: "SCHEDULE",
      dateTitle: "日時と人数を設定",
      completeLine1: "予約タスク完了。",
      completeLine2: "確認メールを見ながら、当日は受付へお進みください。",
    }),
  },
  apple: {
    key: "apple",
    name: "Apple",
    background: "#F5F5F7",
    pattern: "apple",
    primary: "#007AFF",
    secondary: "#34C759",
    gradientFrom: "#007AFF",
    gradientTo: "#5AC8FA",
    heading: "#1D1D1F",
    text: "#1D1D1F",
    muted: "#6E6E73",
    border: "#D2D2D7",
    surface: "#FFFFFF",
    tint: "#EFEFF4",
    chip: "#E8F2FF",
    chipText: "#0057B8",
    shadow: "0 18px 44px rgba(0, 0, 0, 0.08)",
    bgImage: asset("mock-assets/bg/reservation-soft-grid.svg"),
    hero: {
      eyebrow: "Apple Native Booking",
      headline: "静かに確認して、すっと予約。",
      lead: "グループ化されたリストと大きな余白で、iPhoneの設定画面のように落ち着いて進められます。",
      cta: "プランを選ぶ",
      image: asset("mock-assets/booking-top/reservation-lounge.svg"),
      benefits: [
        ["見通しがよい", "画面ごとに情報を整理し、確認の負担を減らします。", CheckCircle2],
        ["自然な操作感", "丸みのあるセルと控えめな区切りで進行できます。", UserRound],
        ["安心感を優先", "予約番号や当日の案内を静かな表示で残します。", ShieldCheck],
      ],
    },
    copy: designSystemCopy({
      planEyebrow: "おすすめ",
      planTitle: "予約する体験",
      planCta: "日時を選ぶ",
      dateEyebrow: "日時",
      dateTitle: "来園日時",
      completeLine1: "予約が完了しました。",
      completeLine2: "当日は予約番号を受付でお知らせください。",
    }),
  },
  carbon: {
    key: "carbon",
    name: "Carbon",
    background: "#F4F4F4",
    pattern: "carbon",
    primary: "#0F62FE",
    secondary: "#198038",
    gradientFrom: "#0F62FE",
    gradientTo: "#262626",
    heading: "#161616",
    text: "#262626",
    muted: "#6F6F6F",
    border: "#C6C6C6",
    surface: "#FFFFFF",
    tint: "#E0E0E0",
    chip: "#D0E2FF",
    chipText: "#0043CE",
    shadow: "none",
    bgImage: asset("mock-assets/bg/reservation-platform.svg"),
    hero: {
      eyebrow: "Carbon Ops Booking",
      headline: "空き状況を管理しながら予約を確定。",
      lead: "KPI、状態、一覧性を重視した、運用者にも説明しやすい予約ダッシュボード型です。",
      cta: "予約データを確認する",
      image: asset("mock-assets/booking-top/reservation-platform.svg"),
      benefits: [
        ["状態が明確", "空き、締切、確認待ちを業務画面として扱えます。", ShieldCheck],
        ["一覧に強い", "候補日や時間をテーブル感覚で比較できます。", CalendarDays],
        ["監査しやすい", "決定理由と確認項目を残しやすい構成です。", CheckCircle2],
      ],
    },
    copy: designSystemCopy({
      planEyebrow: "WORK QUEUE",
      planTitle: "予約対象を選択",
      planCta: "スケジュール確認へ",
      dateEyebrow: "AVAILABILITY",
      dateTitle: "空き枠と人数",
      completeLine1: "予約レコードを確定しました。",
      completeLine2: "受付オペレーション用の確認情報を保存した想定のデモです。",
    }),
  },
  ant: {
    key: "ant",
    name: "Ant",
    background: "#F5F7FA",
    pattern: "ant",
    primary: "#1677FF",
    secondary: "#52C41A",
    gradientFrom: "#1677FF",
    gradientTo: "#0958D9",
    heading: "#1F1F1F",
    text: "#262626",
    muted: "#737373",
    border: "#D9D9D9",
    surface: "#FFFFFF",
    tint: "#F0F5FF",
    chip: "#E6F4FF",
    chipText: "#0958D9",
    shadow: "0 6px 18px rgba(5, 5, 5, 0.08)",
    bgImage: asset("mock-assets/bg/reservation-platform.svg"),
    hero: {
      eyebrow: "Ant Admin Booking",
      headline: "一覧から選んで、効率よく予約。",
      lead: "管理画面のような検索性、フォーム、確認導線で、予約オペレーションを素早く進めます。",
      cta: "予約プラン一覧へ",
      image: asset("mock-assets/booking-top/reservation-calendar.svg"),
      benefits: [
        ["一覧比較", "プラン、時間、支払い方法をコンパクトに比較できます。", CalendarDays],
        ["入力しやすい", "フォーム項目を管理画面らしく整列します。", UserRound],
        ["処理が速い", "選択、確認、確定を明快なボタン階層で進めます。", CheckCircle2],
      ],
    },
    copy: designSystemCopy({
      planEyebrow: "LIST",
      planTitle: "予約プラン一覧",
      planCta: "日時選択へ",
      dateEyebrow: "FORM",
      dateTitle: "日時・人数フォーム",
      completeLine1: "予約を登録しました。",
      completeLine2: "管理画面で確認しやすい予約データとして表示する想定です。",
    }),
  },
  fluent: {
    key: "fluent",
    name: "Fluent",
    background: "#F5F5F5",
    pattern: "fluent",
    primary: "#115EA3",
    secondary: "#0F6CBD",
    gradientFrom: "#115EA3",
    gradientTo: "#0F6CBD",
    heading: "#242424",
    text: "#242424",
    muted: "#616161",
    border: "#D1D1D1",
    surface: "#FFFFFF",
    tint: "#F0F6FC",
    chip: "#EAF4FE",
    chipText: "#0F548C",
    shadow: "0 8px 20px rgba(0, 0, 0, 0.10)",
    bgImage: asset("mock-assets/bg/reservation-soft-grid.svg"),
    hero: {
      eyebrow: "Fluent Workspace Booking",
      headline: "予定と連絡を、ひとつの作業面で。",
      lead: "コマンド、リスト、詳細パネルを組み合わせ、社内ワークスペースになじむ予約画面です。",
      cta: "予約ワークスペースへ",
      image: asset("mock-assets/booking-top/reservation-lounge.svg"),
      benefits: [
        ["作業面が広い", "一覧と詳細を行き来しながら予約できます。", Compass],
        ["通知に強い", "確認や不足情報を穏やかなメッセージで伝えます。", Mail],
        ["チーム利用向き", "担当者が予約内容を確認しやすい構成です。", Users],
      ],
    },
    copy: designSystemCopy({
      planEyebrow: "WORKSPACE",
      planTitle: "予約ワークスペース",
      planCta: "詳細パネルへ進む",
      dateEyebrow: "SCHEDULE",
      dateTitle: "予定と人数",
      completeLine1: "予約を送信しました。",
      completeLine2: "ワークスペース上の通知として確認できる想定です。",
    }),
  },
  primer: {
    key: "primer",
    name: "Primer",
    background: "#F6F8FA",
    pattern: "primer",
    primary: "#0969DA",
    secondary: "#1A7F37",
    gradientFrom: "#0969DA",
    gradientTo: "#24292F",
    heading: "#24292F",
    text: "#24292F",
    muted: "#57606A",
    border: "#D0D7DE",
    surface: "#FFFFFF",
    tint: "#F6F8FA",
    chip: "#DDF4FF",
    chipText: "#0969DA",
    shadow: "0 1px 0 rgba(27, 31, 36, 0.04)",
    bgImage: asset("mock-assets/bg/reservation-soft-grid.svg"),
    hero: {
      eyebrow: "Primer Dev/Event Booking",
      headline: "イベント予約を、状態つきで管理。",
      lead: "ラベル、ステータス、履歴の見え方を重視した、技術者向けイベントや講習に合う予約画面です。",
      cta: "イベントを選ぶ",
      image: asset("mock-assets/booking-top/reservation-calendar.svg"),
      benefits: [
        ["状態ラベル", "受付中、確認待ち、完了をラベルで扱います。", Ticket],
        ["詳細確認", "選択内容や注意事項を記録のように確認できます。", ShieldCheck],
        ["シンプル", "装飾を抑え、情報を読みやすく並べます。", CheckCircle2],
      ],
    },
    copy: designSystemCopy({
      planEyebrow: "ISSUE",
      planTitle: "予約イベント",
      planCta: "予約詳細へ",
      dateEyebrow: "MILESTONE",
      dateTitle: "日時と参加者",
      completeLine1: "予約をクローズしました。",
      completeLine2: "イベント参加チケットとして確認できる想定のデモです。",
    }),
  },
  atlassian: {
    key: "atlassian",
    name: "Atlassian",
    background: "#F7F8F9",
    pattern: "atlassian",
    primary: "#0C66E4",
    secondary: "#22A06B",
    gradientFrom: "#0C66E4",
    gradientTo: "#0055CC",
    heading: "#172B4D",
    text: "#172B4D",
    muted: "#626F86",
    border: "#DCDFE4",
    surface: "#FFFFFF",
    tint: "#F1F2F4",
    chip: "#E9F2FF",
    chipText: "#0C66E4",
    shadow: "0 1px 2px rgba(9, 30, 66, 0.16)",
    bgImage: asset("mock-assets/bg/reservation-soft-grid.svg"),
    hero: {
      eyebrow: "Atlassian Team Booking",
      headline: "チームの予定を、カードで進める。",
      lead: "ワークショップや団体予約を、カード、コメント、状態で共有しやすくする予約画面です。",
      cta: "チーム予約を始める",
      image: asset("mock-assets/booking-top/reservation-family.svg"),
      benefits: [
        ["カードで把握", "予約候補をチームの作業カードのように見比べます。", Users],
        ["相談しやすい", "連絡事項や確認事項をコメント感覚で扱えます。", Mail],
        ["状態管理", "未選択、入力中、確認済みを自然に追えます。", CheckCircle2],
      ],
    },
    copy: designSystemCopy({
      planEyebrow: "BOARD",
      planTitle: "予約カードを選択",
      planCta: "日時カードへ",
      dateEyebrow: "SPRINT",
      dateTitle: "日程と参加人数",
      completeLine1: "予約カードを完了に移動しました。",
      completeLine2: "チームで確認できる予約情報として残る想定です。",
    }),
  },
  slds: {
    key: "slds",
    name: "SLDS",
    background: "#F3F3F3",
    pattern: "slds",
    primary: "#0176D3",
    secondary: "#2E844A",
    gradientFrom: "#0176D3",
    gradientTo: "#032D60",
    heading: "#181818",
    text: "#181818",
    muted: "#706E6B",
    border: "#DDDBDA",
    surface: "#FFFFFF",
    tint: "#F3F2F2",
    chip: "#EAF5FE",
    chipText: "#032D60",
    shadow: "0 2px 4px rgba(0, 0, 0, 0.10)",
    bgImage: asset("mock-assets/bg/reservation-platform.svg"),
    hero: {
      eyebrow: "SLDS CRM Booking",
      headline: "顧客レコードから予約へ。",
      lead: "顧客情報、商談ステップ、関連予約をひとつのレコード画面として扱うCRM寄りの予約UIです。",
      cta: "予約レコードを開く",
      image: asset("mock-assets/booking-top/reservation-platform.svg"),
      benefits: [
        ["顧客中心", "予約者情報をレコードとして確認できます。", UserRound],
        ["パスで進む", "予約ステップを商談パスのように追えます。", CheckCircle2],
        ["関連情報", "プラン、連絡先、支払いを関連リスト感覚で扱います。", Ticket],
      ],
    },
    copy: designSystemCopy({
      planEyebrow: "RECORD",
      planTitle: "予約レコード",
      planCta: "パスを次へ進める",
      dateEyebrow: "PATH",
      dateTitle: "予約パス",
      accountEyebrow: "CONTACT",
      completeLine1: "予約レコードを作成しました。",
      completeLine2: "顧客対応履歴として確認できる想定のデモです。",
    }),
  },
  sap: {
    key: "sap",
    name: "SAP",
    background: "#F7F7F7",
    pattern: "sap",
    primary: "#0070F2",
    secondary: "#188918",
    gradientFrom: "#0070F2",
    gradientTo: "#0A6ED1",
    heading: "#1D2D3E",
    text: "#1D2D3E",
    muted: "#556B82",
    border: "#D9E4EE",
    surface: "#FFFFFF",
    tint: "#EFF4F9",
    chip: "#E5F0FA",
    chipText: "#0A6ED1",
    shadow: "0 2px 8px rgba(34, 54, 73, 0.12)",
    bgImage: asset("mock-assets/bg/reservation-platform.svg"),
    hero: {
      eyebrow: "SAP Process Booking",
      headline: "申請から承認まで見える予約。",
      lead: "予約を業務オブジェクトとして扱い、承認、確認、ステータスを重視するプロセス型UIです。",
      cta: "予約オブジェクトを開く",
      image: asset("mock-assets/booking-top/reservation-platform.svg"),
      benefits: [
        ["プロセス重視", "予約の状態と次アクションを明確にします。", ShieldCheck],
        ["承認に強い", "団体予約や確認が必要な予約に向きます。", CheckCircle2],
        ["項目整理", "基本情報、参加者、支払いをセクションで分けます。", CalendarDays],
      ],
    },
    copy: designSystemCopy({
      planEyebrow: "OBJECT PAGE",
      planTitle: "予約オブジェクト",
      planCta: "日程セクションへ",
      dateEyebrow: "PROCESS",
      dateTitle: "予約プロセス",
      confirmEyebrow: "APPROVAL",
      completeLine1: "予約プロセスが完了しました。",
      completeLine2: "承認済みオブジェクトとして参照できる想定です。",
    }),
  },
  fds: {
    key: "fds",
    name: "FDS",
    background: "#F7F8FA",
    pattern: "fds",
    primary: "#005BAC",
    secondary: "#008A4B",
    gradientFrom: "#005BAC",
    gradientTo: "#003F7F",
    heading: "#1F2933",
    text: "#1F2933",
    muted: "#5B6773",
    border: "#CBD5E1",
    surface: "#FFFFFF",
    tint: "#EEF2F7",
    chip: "#E8F3FF",
    chipText: "#005BAC",
    shadow: "0 4px 12px rgba(31, 41, 51, 0.08)",
    bgImage: asset("mock-assets/bg/reservation-platform.svg"),
    hero: {
      eyebrow: "FDS Japanese Booking",
      headline: "現場で使いやすい予約管理。",
      lead: "日本の業務画面らしい密度と分かりやすさで、予約受付・確認・変更に強い画面です。",
      cta: "予約受付を開始",
      image: asset("mock-assets/booking-top/reservation-calendar.svg"),
      benefits: [
        ["実務向き", "一覧、入力、確認をコンパクトに整理します。", CheckCircle2],
        ["日本語に強い", "長めの項目名や注意書きも読みやすく扱います。", ShieldCheck],
        ["受付で使える", "当日確認に必要な情報を見つけやすくします。", LifeBuoy],
      ],
    },
    copy: designSystemCopy({
      planEyebrow: "予約受付",
      planTitle: "予約プラン選択",
      planCta: "日時入力へ進む",
      dateEyebrow: "日時・人数",
      dateTitle: "予約条件入力",
      accountEyebrow: "お客様情報",
      completeLine1: "予約受付が完了しました。",
      completeLine2: "受付確認用の予約番号を控えてください。",
    }),
  },
};

export const patternFallback = {
  vibrant: "bento",
  premium: "studio",
  "ui-clarity": "studio",
  "visual-booking": "craft",
  puerto: "puerto",
  neumorphism: "bento",
  glassmorphism: "craft",
};

export const plans = [
  {
    id: "workshop",
    title: "季節のワークショップ",
    pr: "手ぶらで参加できる90分の体験。",
    image: asset("mock-assets/booking-top/reservation-calendar.svg"),
  },
  {
    id: "lunch",
    title: "ランチ付き見学プラン",
    pr: "見学と食事をまとめて予約。",
    image: asset("mock-assets/booking-top/reservation-lounge.svg"),
  },
  {
    id: "family",
    title: "ファミリー半日コース",
    pr: "小さなお子さま連れでも進めやすい定番コース。",
    image: asset("mock-assets/booking-top/reservation-family.svg"),
  },
];

export const dateOptions = ["6/6 土", "6/7 日", "6/13 土", "6/14 日"];
export const timeOptions = ["10:00", "11:00", "12:00", "13:00"];

export const paymentOptions = [
  ["localPay", "当日受付払い", "受付で内容を確認して支払い。", WalletCards],
  ["credit", "事前決済（サンプル）", "画面確認用の支払い表示です。", CreditCard],
];
