import {
  CalendarDays,
  Camera,
  CheckCircle2,
  CreditCard,
  Flower2,
  PartyPopper,
  Salad,
  ShieldCheck,
  Sprout,
  Ticket,
  Users,
  WalletCards,
} from "lucide-react";

export const patterns = {
  bento: {
    key: "bento",
    name: "旬のベントー",
    background: "#FAF5EE",
    pattern: "none",
    primary: "#D45B2C",
    secondary: "#2D8C5A",
    gradientFrom: "#E06830",
    gradientTo: "#B84820",
    heading: "#2A1A0E",
    text: "#302418",
    muted: "#7A6A58",
    border: "#E8DCC8",
    surface: "#FFFFFF",
    tint: "#F5EDE0",
    chip: "#E8F4E0",
    chipText: "#2D7A4A",
    shadow: "0 8px 24px rgba(80,50,20,0.1)",
    bgImage: "/mock-assets/bg/road-trip-pexels.jpg",
    hero: {
      eyebrow: "蒲郡オレンジパーク 2026",
      headline: "旬を選んで、蒲郡へ。",
      lead: "家族の週末に、甘い予定を。",
      cta: "旬のチケットを見る",
      image: "/mock-assets/booking-top/orange-tree-couple-pexels-tran-le-tuan.jpg",
      benefits: [
        ["季節を選ぶ", "いまだけの味わいを、旅のきっかけに。", Ticket],
        ["旅支度を軽く", "行きたい気持ちで、すぐ予約。", CheckCircle2],
        ["蒲郡らしさ", "柑橘と緑に囲まれる一日。", Flower2],
      ],
    },
    copy: {
      planEyebrow: "旬のプラン",
      planTitle: "旬のプラン",
      planCta: "このプランにする",
      dateEyebrow: "日時と人数",
      dateTitle: "日時と人数",
      dateCta: "予約者情報へ",
      accountEyebrow: "予約者情報",
      accountTitle: "予約者情報",
      memoEyebrow: "連絡事項",
      memoTitle: "連絡事項",
      paymentEyebrow: "お支払い",
      paymentTitle: "支払い方法",
      paymentCta: "この内容で確認する",
      confirmEyebrow: "予約確認",
      confirmTitle: "予約内容の確認",
      confirmCta: "この内容で予約する",
      completeLine1: "予約完了。",
      completeLine2: "当日をお楽しみに。蒲郡で素敵な一日をお過ごしください。",
    },
  },
  craft: {
    key: "craft",
    name: "収穫手帖",
    background: "#FAF6F0",
    pattern: "paper",
    primary: "#FF914D",
    secondary: "#6F8F6A",
    gradientFrom: "#FF914D",
    gradientTo: "#D35400",
    heading: "#2B2A27",
    text: "#2B2A27",
    muted: "#6F675C",
    border: "#2B2A27",
    surface: "#FFFDF8",
    tint: "#F3E9D8",
    chip: "#D2E9CB",
    chipText: "#2F653A",
    shadow: "5px 5px 0 #2B2A27",
    bgImage: "/mock-assets/bg/orchard-pexels.jpg",
    hero: {
      eyebrow: "蒲郡オレンジパーク",
      headline: "今日の実りを、予定に貼っておく。",
      lead: "果樹園の空気まで楽しみにしながら、家族の週末にぴったりの体験を選べます。",
      cta: "旬の体験を選ぶ",
      image: "/mock-assets/booking-top/orange-orchard-worker-pexels.jpg",
      benefits: [
        ["旬を持ち帰る気分", "枝先の色づきや畑の香りを、予約前から少しだけ。", Sprout],
        ["家族で決めやすい", "日付と人数を選ぶだけで、週末のおでかけが形になります。", CheckCircle2],
        ["蒲郡の一日", "果物狩りのあとも、食事や寄り道までゆっくり楽しめます。", Flower2],
      ],
    },
    copy: {
      planEyebrow: "旬の体験",
      planTitle: "どの実りを楽しむ？",
      planCta: "この体験で日時へ",
      dateEyebrow: "来園日",
      dateTitle: "行きたい日を選ぶ",
      dateCta: "予約者情報へ",
      accountEyebrow: "ご連絡先",
      accountTitle: "予約者情報",
      memoEyebrow: "ご要望",
      memoTitle: "来園前のひとこと",
      paymentEyebrow: "お支払い",
      paymentTitle: "支払い方法",
      paymentCta: "内容を確認する",
      confirmEyebrow: "最終確認",
      confirmTitle: "予約内容の確認",
      confirmCta: "この内容で予約する",
      completeLine1: "旬の予定が入りました。",
      completeLine2: "当日は蒲郡オレンジパークで、採れたてのおいしさを楽しんでください。",
    },
  },
  studio: {
    key: "studio",
    name: "果樹園ギャラリー",
    background: "#FBFBF9",
    pattern: "grid",
    primary: "#C85A32",
    secondary: "#B28E46",
    gradientFrom: "#C85A32",
    gradientTo: "#0F141C",
    heading: "#111111",
    text: "#1A1A19",
    muted: "#72716B",
    border: "#E2E2DC",
    surface: "#FFFFFF",
    tint: "#F2F1EC",
    chip: "#F6F2E8",
    chipText: "#8A4A30",
    shadow: "0 24px 70px rgba(15,20,28,0.08)",
    bgImage: "/mock-assets/bg/road-trip-pexels.jpg",
    hero: {
      eyebrow: "旬を眺めて選ぶ",
      headline: "果樹園で過ごす時間を、ゆっくり選ぶ。",
      lead: "写真を眺めながら、食べたいもの、過ごしたい時間、行きたい日を落ち着いて決められます。",
      cta: "プランを見てみる",
      image: "/mock-assets/booking-top/orange-tree-couple-pexels-tran-le-tuan.jpg",
      benefits: [
        ["写真で選べる", "その日の楽しみ方を想像しながら、プランを比べられます。", Ticket],
        ["景色も楽しみ", "果樹園の緑や実りの色まで、来園前の楽しみに。", Camera],
        ["ゆっくり確かめる", "日時、人数、お支払いまで、ひとつずつ確認して進めます。", ShieldCheck],
      ],
    },
    copy: {
      planEyebrow: "おすすめプラン",
      planTitle: "気になるプランを選ぶ",
      planCta: "このプランで日時へ",
      dateEyebrow: "来園日時",
      dateTitle: "行きたい日時を選ぶ",
      dateCta: "予約者情報へ",
      accountEyebrow: "ご連絡先",
      accountTitle: "予約者情報",
      memoEyebrow: "ご要望",
      memoTitle: "連絡事項",
      paymentEyebrow: "お支払い",
      paymentTitle: "支払い方法",
      paymentCta: "予約内容を確認する",
      confirmEyebrow: "確認",
      confirmTitle: "予約内容の確認",
      confirmCta: "予約を確定する",
      completeLine1: "予約を承りました。",
      completeLine2: "当日は果樹園の景色と旬のおいしさを、ゆっくりお楽しみください。",
    },
  },
};

export const patternFallback = {
  "fruit-trip": "bento",
  "family-fun": "bento",
  "seasonal-ticket": "bento",
  vibrant: "bento",
  premium: "studio",
  festival: "bento",
  "ui-clarity": "studio",
  "visual-travel": "craft",
  neumorphism: "bento",
  glassmorphism: "craft",
};

export const plans = [
  {
    id: "cherry",
    title: "さくらんぼ狩り",
    pr: "枝先の旬を、その場で。",
    image: "/mock-assets/booking-top/orange-orchard-worker-pexels.jpg",
  },
  {
    id: "kama",
    title: "釜飯とフルーツ狩り",
    pr: "おいしい食事と旬の味わいを。",
    image: "/mock-assets/booking-top/orange-tree-couple-pexels-tran-le-tuan.jpg",
  },
  {
    id: "family",
    title: "みんなで収穫体験",
    pr: "家族で採って食べて笑う一日。",
    image: "/mock-assets/booking-top/family-strawberry-harvest-pexels-paloma-rodriguez.jpg",
  },
];

export const dateOptions = ["5/24 土", "5/25 日", "5/31 土", "6/1 日"];
export const timeOptions = ["10:00", "11:00", "12:00", "13:00"];

export const paymentOptions = [
  ["localPay", "当日現地払い", "受付でお支払い。", WalletCards],
  ["credit", "クレジットカード", "事前決済で、当日は身軽に。", CreditCard],
];
